name: "STAGING ENV: Deploy Lambda"

on:
  push:
    branches:
      - staging

jobs:
  deploy-terraform-staging:
    name: "Plan & Deploy Infra in Stage environment"
    runs-on: ubuntu-latest
    env:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-1
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.0.0

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup CDK
        run: python3 -m pip install -r requirements.txt

      - name: CDK Bootstrap
        id: init
        run: cdk bootstrap

      - name: CDK Check Difference
        id: diff
        run: cdk diff

      - name: CDK Deploy
        id: deploy
        run: cdk deploy
